apiVersion: v1
kind: Pod
metadata:
  name: gpu-job
  labels:
    app: gpu-job
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
  nodeSelector:
    tier: backend
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
