apiVersion: v1
kind: Pod
metadata:
  name: maintenance-job
  labels:
    app: maintenance
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: k3d-labels-taints-cluster-server-0
