apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-with-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-volume
  template:
    metadata:
      labels:
        app: nginx-volume
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        hostPath:
          path: /data
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-volume-service
spec:
  type: NodePort
  selector:
    app: nginx-volume
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080