apiVersion: v1
kind: Pod
metadata:
  name: volume-test-pod
spec:
  containers:
  - name: test-container
    image: alpine:latest
    command: ['sleep', '3600']
    volumeMounts:
    - name: data-volume
      mountPath: /data
    - name: config-volume
      mountPath: /config
  volumes:
  - name: data-volume
    hostPath:
      path: /data
      type: Directory
  - name: config-volume
    hostPath:
      path: /shared-config
      type: Directory